#line 2 "scanner.c"

#line 4 "scanner.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 68
#define YY_END_OF_BUFFER 69
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[275] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,   15,   15,
        0,    0,    0,    0,   19,   19,   69,   67,   24,    1,
       54,   67,   63,   67,    3,   52,   53,   64,   46,   64,
       67,   63,   59,   49,   66,   61,   66,   62,   62,   47,
       48,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   50,   51,    9,    6,    6,    7,    5,    5,   12,
       68,   12,   11,   12,   68,   15,   14,   14,   15,   18,
       16,   16,   18,   19,   24,   66,    0,   58,   58,   56,
        0,   55,    2,    0,    0,   65,   26,   60,   21,    0,
       59,    0,   59,   25,   25,   62,    0,   62,   62,   62,

       62,   62,   62,   33,   62,   62,   62,   30,   62,   62,
       62,   62,   62,    0,    0,    0,    0,   11,    0,   15,
        0,   15,    0,   16,   16,    0,   17,   19,    0,    0,
       58,   58,    0,    0,    4,    0,    0,   26,   26,   26,
       60,    0,   21,   21,   21,   21,    0,   20,   20,    0,
        0,   26,    0,   25,   25,    0,   25,    0,   27,   62,
       62,   62,   62,   62,   62,   62,   62,   32,   36,   62,
       62,   62,   62,    8,    0,   13,   13,   15,   13,   58,
        0,   57,   57,   56,    0,    0,   57,   57,    0,   10,
       45,   44,   26,    0,   26,   26,   60,   21,    0,   21,

       21,    0,   21,   21,   21,   21,   20,   20,   20,   20,
       26,   27,   62,   42,   37,   62,   62,   62,   31,   62,
       62,   62,   35,   62,    0,   57,   57,   57,    0,   26,
        0,    0,   21,   21,   20,   20,   21,   21,   21,    0,
        0,   20,    0,   39,   62,   62,   62,   34,   62,   62,
       38,    0,   56,    0,   26,   26,    0,    0,   21,   21,
       22,   22,   20,   20,   20,   62,   62,   40,   41,   28,
       62,   29,   43,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    1,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    6,    7,    1,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,    1,   20,   21,
       22,   23,    1,    1,   24,   24,   24,   24,   25,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       26,   27,   28,    1,    1,    1,   29,   30,   31,   32,

       33,   34,   35,   36,   37,   35,   38,   39,   35,   40,
       41,   35,   35,   42,   43,   44,   45,   46,   47,   35,
       35,   35,   48,    1,   49,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[50] =
    {   0,
        1,    2,    3,    1,    4,    1,    1,    1,    1,    5,
        1,    1,    1,    1,    1,    1,    2,    1,    6,    1,
        1,    1,    1,    7,    7,    1,    8,    1,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    1,    1
    } ;

static const flex_int16_t yy_base[308] =
    {   0,
        0,    0,   49,    0,   96,   97,    0,    0,  102,  103,
      106,  107,    0,    0,  644,  626,  616,  820,  111,  820,
      590,  111,  820,  600,  107,  820,  820,  594,  820,  591,
      108,  108,  120,  820,  580,  523,  522,    0,  117,  820,
      820,  501,   99,  108,  128,  107,  116,  509,  494,  499,
      503,  820,  820,  820,  820,  820,  820,  820,  494,  152,
      155,  158,  161,  166,  820,    0,  820,    0,  149,  167,
      820,  171,  178,    0,  173,  820,  187,  820,  175,  181,
      184,  820,  820,    0,  185,  820,  180,  184,  202,  195,
      820,  187,  208,  518,  202,    0,  517,  207,  502,  491,

      504,  492,  497,  485,  486,  487,  485,    0,  482,  481,
      477,  473,  472,  487,  225,  231,  232,  237,  240,    0,
      243,  246,  250,  820,  251,  257,  258,    0,  263,  266,
      269,  274,  275,  474,  820,  471,  462,  264,  267,  270,
      275,  290,  294,  307,  308,  311,  312,  820,  320,  323,
      327,  314,  321,    0,  450,  446,  317,  325,  436,  423,
      416,  406,  394,  400,  394,  387,  388,    0,    0,  368,
      365,  366,  355,  820,  340,  820,  343,  346,  350,  353,
      354,  820,  357,  360,  361,  364,  820,  365,  368,  383,
      820,  820,  355,  358,  359,  363,  366,  381,  384,  397,

      398,  401,  402,  409,  413,  418,  422,  427,    0,  430,
      417,  371,  341,    0,    0,  315,  282,  283,    0,  275,
      263,  260,    0,  255,  434,  258,  438,  441,  428,  434,
      437,  458,  461,  470,  455,  473,  474,  477,  482,  485,
      486,  489,  490,    0,  233,  218,  217,    0,  191,  187,
        0,  291,  820,  216,  479,  482,  486,  497,  503,  515,
      820,  518,  820,  519,    0,  106,   99,    0,    0,    0,
       99,    0,    0,  820,  546,  555,  564,  573,  582,  591,
      596,  604,  608,  617,  626,  635,  644,  653,  662,  667,
      676,  685,  689,  698,  707,  716,  725,  734,  743,  747,

      756,  765,  774,  783,  792,  801,  810
    } ;

static const flex_int16_t yy_def[308] =
    {   0,
      274,    1,  274,    3,  275,  275,  276,  276,  277,  277,
      278,  278,  276,  276,  279,  279,  274,  274,  274,  274,
      274,  280,  274,  274,  281,  274,  274,  274,  274,  274,
      274,  274,  282,  274,  274,  274,  274,  283,  283,  274,
      274,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  274,  274,  274,  274,  274,  274,  274,  274,  284,
      284,  284,  284,  284,  274,  285,  274,  285,  285,  286,
      274,  286,  286,  287,  274,  274,  280,  274,  288,  288,
      280,  274,  274,  289,  290,  274,  274,  274,  291,  292,
      274,  274,  282,  293,  293,  283,  274,  283,  283,  283,

      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  274,  284,  284,  284,  284,  284,  285,
      294,  295,  286,  274,  286,  286,  286,  287,  288,  288,
      296,  297,  280,  289,  274,  290,  290,  274,  274,  274,
      274,  274,  291,  298,  291,  299,  292,  274,  292,  292,
      292,  274,  274,  300,  293,  274,  300,  274,  274,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  274,  294,  274,  294,  295,  295,  301,
      296,  274,  301,  301,  296,  297,  274,  297,  297,  289,
      274,  274,  274,  274,  274,  274,  274,  299,  298,  298,

      298,  302,  291,  298,  291,  291,  303,  291,  304,  305,
      274,  274,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  301,  306,  301,  297,  274,  274,
      274,  298,  298,  298,  307,  298,  303,  307,  303,  304,
      305,  305,  305,  283,  283,  283,  283,  283,  283,  283,
      283,  306,  274,  306,  274,  274,  274,  307,  307,  307,
      274,  304,  274,  305,  304,  283,  283,  283,  283,  283,
      283,  283,  283,    0,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,

      274,  274,  274,  274,  274,  274,  274
    } ;

static const flex_int16_t yy_nxt[870] =
    {   0,
       18,   19,   20,   19,   18,   21,   22,   23,   24,   25,
       26,   27,   23,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   18,   41,   38,   42,
       43,   44,   45,   46,   38,   38,   47,   38,   38,   38,
       38,   48,   49,   38,   38,   50,   51,   52,   53,   54,
       54,   55,   54,   56,   54,   54,   54,   54,   57,   54,
       54,   54,   54,   54,   54,   54,   54,   58,   54,   54,
       54,   54,   58,   58,   54,   59,   54,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   54,   54,   61,   61,

       62,   62,   63,   63,   67,   67,   68,   68,   71,   71,
       72,   72,   75,   78,   75,   79,   83,   80,   73,   73,
       89,   91,   64,   64,   87,   90,   88,  100,   69,   69,
       97,  273,   97,   85,  101,   98,   92,   81,   93,  102,
      103,   97,  272,   97,   95,  106,   98,  107,  104,  108,
      271,  121,   95,  122,  116,  109,  117,  116,  118,  117,
      116,  118,  117,  116,  118,  117,  105,  118,  116,  124,
      117,  125,  118,  124,   75,  125,   75,   78,  119,   79,
      124,  119,  125,   78,  119,   79,  131,  119,  132,   78,
      126,   79,  119,   80,  135,  127,  138,  148,  139,  149,

      140,  130,  141,  152,  144,  141,  145,  130,  142,   91,
      133,  153,  150,   81,  146,  156,  142,  156,  252,  153,
      157,  151,  270,  159,   92,   98,   93,  116,  137,  117,
      269,  118,   95,  116,  116,  117,  117,  118,  118,  116,
       95,  117,  116,  118,  117,  176,  118,  177,  176,  268,
      179,  119,  124,  124,  125,  125,  267,  119,  119,  124,
      124,  125,  125,  119,  253,   78,  119,   79,  180,  126,
      132,  182,  266,  183,  127,  184,  187,  180,  188,  132,
      138,   80,  193,  194,  254,  139,  195,  251,  196,  130,
      250,  140,  130,  141,  153,  185,  144,  253,  145,  142,

      189,   81,  153,  156,  249,  156,  198,  142,  197,  200,
      144,  201,  145,  204,  148,  205,  149,  254,  248,  202,
      198,  247,  148,  206,  149,  148,  246,  149,  207,  209,
      138,  210,  211,  159,   97,  157,   97,  208,  151,  158,
      150,  159,  176,  158,  177,  176,  151,  177,  176,  151,
      179,  245,  176,  151,  179,  182,  182,  183,  183,  182,
      184,  183,  182,  226,  183,  183,  187,  187,  188,  188,
      227,  138,  228,  193,   87,  138,  229,  230,  244,  231,
      185,  196,  159,  204,  197,  205,  200,  153,  201,  212,
      189,  189,  190,  224,  189,  153,  202,  223,  207,  200,

      200,  201,  201,  233,  144,  234,  145,  208,  222,  202,
      202,  200,  221,  201,  198,  144,  220,  145,  235,  219,
      144,  202,  145,  218,  238,  198,  239,  236,  217,  144,
      146,  145,  148,  231,  242,  196,  182,  216,  183,  198,
      182,  153,  183,  187,   87,  188,  229,  215,  214,  153,
      255,  213,  256,  152,  212,  257,  243,  259,  153,  260,
      200,  153,  201,  200,  197,  201,  153,  189,  154,  153,
      202,  192,  200,  202,  201,  200,  238,  201,  239,  259,
      191,  260,  202,  190,  238,  202,  239,  261,  263,  262,
      264,  263,  265,  264,  264,  195,  174,  256,  255,  259,

      256,  260,  140,  153,  257,  259,  153,  260,  173,  172,
      153,  153,  243,  171,  153,  243,  243,  259,  153,  260,
      261,  263,  262,  264,  170,  169,  168,  167,  166,  165,
      164,  163,  162,  161,  160,  158,  154,  114,  113,  112,
      111,  110,   99,   76,   76,  243,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   77,   77,   77,   77,   77,   77,   77,   77,   77,

       84,   76,   84,   84,   84,   94,   86,   86,   82,   94,
       94,   76,   94,   96,   96,  274,   96,  115,  115,  115,
      115,  115,  115,  115,  115,  115,  120,  120,   65,  120,
      120,  120,  120,  120,  120,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  128,  128,   65,  128,  128,  128,
      128,  128,  128,  129,  129,  129,  129,  129,  129,  129,
      129,  129,  134,  134,  274,  134,  134,  134,  134,  134,
      134,  136,  274,  274,  274,  136,  143,  143,  143,  143,
      143,  143,  143,  143,  143,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  155,  155,  274,  155,  175,  175,

      175,  175,  175,  175,  175,  175,  175,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  181,  181,  181,  181,
      181,  181,  181,  181,  181,  186,  186,  186,  186,  186,
      186,  186,  186,  186,  199,  199,  199,  199,  199,  199,
      199,  199,  199,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  154,  154,  274,  154,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  240,  240,  274,  240,  240,  240,  240,
      240,  240,  241,  241,  241,  241,  241,  241,  241,  241,

      241,  252,  252,  274,  274,  252,  252,  252,  252,  252,
      258,  258,  258,  258,  258,  258,  258,  258,  258,   17,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274
    } ;

static const flex_int16_t yy_chk[870] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    5,    6,

        5,    6,    5,    6,    9,   10,    9,   10,   11,   12,
       11,   12,   19,   22,   19,   22,   25,   22,   11,   12,
       32,   33,    5,    6,   31,   32,   31,   43,    9,   10,
       39,  271,   39,   25,   43,   39,   33,   22,   33,   43,
       44,   45,  267,   45,   33,   46,   45,   46,   44,   47,
      266,   69,   33,   69,   60,   47,   60,   61,   60,   61,
       62,   61,   62,   63,   62,   63,   45,   63,   64,   70,
       64,   70,   64,   72,   75,   72,   75,   79,   60,   79,
       73,   61,   73,   80,   62,   80,   81,   63,   81,   77,
       73,   77,   64,   77,   85,   73,   87,   90,   87,   90,

       88,   79,   88,   92,   89,   92,   89,   80,   88,   93,
       81,   92,   90,   77,   89,   95,   88,   95,  254,   92,
       95,   90,  250,   98,   93,   98,   93,  115,   85,  115,
      249,  115,   93,  116,  117,  116,  117,  116,  117,  118,
       93,  118,  119,  118,  119,  121,  119,  121,  122,  247,
      122,  115,  123,  125,  123,  125,  246,  116,  117,  126,
      127,  126,  127,  118,  226,  129,  119,  129,  130,  126,
      130,  131,  245,  131,  126,  131,  132,  133,  132,  133,
      138,  133,  138,  139,  226,  139,  140,  224,  140,  129,
      222,  141,  130,  141,  140,  131,  143,  252,  143,  141,

      132,  133,  140,  142,  221,  142,  143,  141,  142,  144,
      145,  144,  145,  146,  147,  146,  147,  252,  220,  144,
      145,  218,  149,  146,  149,  150,  217,  150,  146,  151,
      152,  151,  152,  157,  153,  157,  153,  146,  147,  153,
      150,  158,  175,  158,  175,  177,  149,  177,  178,  150,
      178,  216,  179,  151,  179,  180,  181,  180,  181,  183,
      181,  183,  184,  185,  184,  185,  186,  188,  186,  188,
      189,  193,  189,  193,  194,  195,  194,  195,  213,  196,
      181,  196,  197,  198,  197,  198,  199,  196,  199,  212,
      186,  188,  190,  173,  189,  196,  199,  172,  198,  200,

      201,  200,  201,  202,  203,  202,  203,  198,  171,  200,
      201,  204,  170,  204,  203,  205,  167,  205,  202,  166,
      206,  204,  206,  165,  207,  205,  207,  202,  164,  208,
      206,  208,  210,  211,  210,  211,  225,  163,  225,  208,
      227,  211,  227,  228,  229,  228,  229,  162,  161,  211,
      230,  160,  230,  231,  159,  231,  210,  235,  230,  235,
      232,  231,  232,  233,  156,  233,  230,  228,  155,  231,
      232,  137,  234,  233,  234,  236,  237,  236,  237,  238,
      136,  238,  234,  134,  239,  236,  239,  240,  241,  240,
      241,  242,  243,  242,  243,  255,  114,  255,  256,  258,

      256,  258,  257,  255,  257,  259,  256,  259,  113,  112,
      257,  255,  241,  111,  256,  242,  243,  260,  257,  260,
      262,  264,  262,  264,  110,  109,  107,  106,  105,  104,
      103,  102,  101,  100,   99,   97,   94,   59,   51,   50,
       49,   48,   42,   37,   36,  264,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  280,  280,  280,  280,  280,  280,  280,  280,  280,

      281,   35,  281,  281,  281,  282,   30,   28,   24,  282,
      282,   21,  282,  283,  283,   17,  283,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  285,  285,   16,  285,
      285,  285,  285,  285,  285,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  287,  287,   15,  287,  287,  287,
      287,  287,  287,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  289,  289,    0,  289,  289,  289,  289,  289,
      289,  290,    0,    0,    0,  290,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  293,  293,    0,  293,  294,  294,

      294,  294,  294,  294,  294,  294,  294,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  299,  299,  299,  299,  299,  299,  299,
      299,  299,  300,  300,    0,  300,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  304,  304,    0,  304,  304,  304,  304,
      304,  304,  305,  305,  305,  305,  305,  305,  305,  305,

      305,  306,  306,    0,    0,  306,  306,  306,  306,  306,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"







#line 12 "scanner.l"
#include<stdio.h>
#include<stdlib.h>
#include<iostream>
#include "SymbolTable.cpp"

using namespace std;



int line_count=1;
int error_count=0;
SymbolTable sTable(7);
string c;
string String_literals1;
string String_literals2;

string const_character;


FILE *logout;
FILE *tokenout;

#line 762 "scanner.c"
#line 763 "scanner.c"

#define INITIAL 0
#define END_WITH_SQ 1
#define END_WITH_DQ 2
#define STRING_LIT 3
#define SLINECOMMENT 4
#define MULTILINECOMMENT 5
#define MSCOMMENT 6
#define DUMMY 7

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 111 "scanner.l"


#line 990 "scanner.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 275 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 820 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 113 "scanner.l"
{line_count++;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 118 "scanner.l"
{
			printf("\nEmpty character constant error %d: %s\n",line_count,yytext);
			fprintf(logout,"\nError at line no %d: Empty character constant error %s\n",line_count,yytext);
			error_count++;
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 124 "scanner.l"
{
	
	string str(yytext);
	c = str;
	BEGIN END_WITH_SQ;

	}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 132 "scanner.l"
{

			printf("sq UNFINISHED Error at line %d: %s\n",line_count,yytext);
			fprintf(logout,"\nError at line no %d: Unterminated character %s\n",line_count,yytext);
			error_count++;
			}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 139 "scanner.l"
{
						    string str(yytext);
						    const_character = str;
						    c = c + str;

						  }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 146 "scanner.l"
{
							char output[c.length()+1];
							strcpy(output,c.c_str());
							printf("\nError at line no %d: Unterminated character %s\n",line_count, output);
							fprintf(logout,"\nError at line no %d: Unterminated character %s\n",line_count, output);
							line_count++;
							error_count++;
							BEGIN INITIAL;

					      }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 158 "scanner.l"
{

			char output[const_character.length()+1];

			strcpy(output,const_character.c_str());
			printf("<CONST_C, %s> at Line: %d\n",output,line_count);
			fprintf(tokenout,"<CONST_CHAR, %s> ",output);
		   	fprintf(logout,"\nLine no %d: Token <CONST_CHAR> Lexeme %s found\n",line_count,yytext);

			//fprintf(logout,"Line no %d: TOKEN <CONST_CHAR> Lexeme %s found\n",line_count,const_character);
			BEGIN INITIAL;
		       
		        }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 172 "scanner.l"
{

	cout<<"CONST_CHAR: \t\n";
	fprintf(logout,"\nLine no %d: Token <CONST_CHAR> Lexeme \t found\n",line_count);


	BEGIN INITIAL;
}		        
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 180 "scanner.l"
{
								printf("UnknownError ERROR at Line: %d\n",line_count);

								
							fprintf(logout,"\nLine no: %d UnknownError %s\n",line_count, yytext);
							error_count++;
								BEGIN INITIAL;
						  
						  }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 194 "scanner.l"
{
							printf("\nError at line no %d: Multi character constant error %s\n",line_count,yytext);
							//fprintf(tokenout,"<CONST_MULTI_CHAR, %s> ",yytext);
							fprintf(logout,"\nError at line no %d: Multi character constant error %s\n",line_count,yytext);
			//sTable.push("COsMMA",yytext);
							error_count++;
									BEGIN INITIAL;

							    }
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 206 "scanner.l"
{
							printf("LITERALS FOUND: <%s> \n",yytext);
							fprintf(tokenout,"<STRING, %s> ",yytext);
							fprintf(logout,"\nLine no %d: TOKEN <STRING> Lexeme %s found\n",line_count,yytext);
			//sTable.push("COMMA",yytext);
							BEGIN INITIAL;
					     }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 214 "scanner.l"
{printf("DQ NOT finished"); BEGIN INITIAL;}
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 222 "scanner.l"
{printf("we r here\n");line_count++;line_count++; BEGIN INITIAL;}
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 223 "scanner.l"
{printf("we r here\n");line_count++; BEGIN INITIAL;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 224 "scanner.l"
{}
	YY_BREAK
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 227 "scanner.l"
{printf("we r multi\n");line_count++;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 228 "scanner.l"
{printf("i m visited\n");BEGIN INITIAL;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 229 "scanner.l"
{printf("not finished\n"); BEGIN DUMMY;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 231 "scanner.l"
{printf("i m in DUMMY\n"); BEGIN INITIAL;}
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 238 "scanner.l"
{

	printf("NO ACTION\n %s\n",yytext);
	string str(yytext);
	char str1[str.length()];

	strcpy(str1,str.c_str());

	for(int i=0;i<str.length();i++){
		if (str1[i]=='\n') {
			line_count++;
		}
	}


}
	YY_BREAK
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
#line 255 "scanner.l"
{
					string str(yytext);
					char out[str.length()];
					strcpy(out,str.c_str());
					if(out[str.length()-1] != '/' && out[str.length()-2] != '*'){
						printf("\ncomment not finished Error! at line:%d \n",line_count);
						fprintf(logout,"\nError at line no %d: Unterminated Comment %s",line_count,yytext);
						error_count++;
					}
					for (int i=0;i<str.length() ;i++ ) {
						
						if (out[i]=='\n'|| out[i]=='\r') {
							line_count++;
						}
							
				   }
				}
	YY_BREAK
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
#line 273 "scanner.l"
{printf("kas\n");line_count+=2;}
	YY_BREAK
case 23:
/* rule 23 can match eol */
YY_RULE_SETUP
#line 274 "scanner.l"
{printf("single\n");line_count++;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 276 "scanner.l"
{}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 278 "scanner.l"
{printf("\n%s is an IDENTIFIER_ERROR\n",yytext);
					fprintf(logout,"\nError at line no %d: Invalid prefix on ID or invalid suffix on Number %s\n",line_count,yytext);

					error_count++;
				
					}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 284 "scanner.l"
{printf("\n%s DECIMALPOINTER_ERROR\n",yytext);
						fprintf(logout,"\nError at line no %d: Too many decimal points %s\n",line_count,yytext);
						error_count++;
					}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 289 "scanner.l"
{printf("\n%s is an ILL_FORMAT_ERROR\n",yytext);
				
					fprintf(logout,"\nError at line no %d: Ill formed Number %s\n",line_count,yytext);
					error_count++;


				}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 305 "scanner.l"
{printf(" <%s> found\n",yytext);
		  //outputfile<<"<SWITCH> ";	
			fprintf(tokenout,"<SWITCH> ");
			fprintf(logout,"\nLine no %d: Token <SWITCH> Lexeme %s found\n",line_count,yytext);
			//sTable.push("SWITCH",yytext);
		  }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 311 "scanner.l"
{printf(" <%s> found\n",yytext);  
			//outputfile<<"<DEFAULT> ";
			fprintf(tokenout,"<DEFAULT> ");
			fprintf(logout,"\nLine no %d: Token <DEFAULT> Lexeme %s found\n",line_count,yytext);
		
        }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 317 "scanner.l"
{printf(" <%s> found\n",yytext);
		//outputfile<<"<IF> "; 
			fprintf(tokenout,"<IF> ");
			fprintf(logout,"\nLine no %d: Token <IF> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 322 "scanner.l"
{printf(" <%s> found\n",yytext);
			//	outputfile<<"<ELSE> ";
		    fprintf(tokenout,"<ELSE> ");
			fprintf(logout,"\nLine no %d: Token <ELSE> Lexeme %s found\n",line_count,yytext);
			}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 327 "scanner.l"
{printf(" <%s> found\n",yytext);
				//outputfile<<"<FOR> ";
		    fprintf(tokenout,"<FOR>");
			fprintf(logout,"\nLine no %d: Token <FOR> Lexeme %s found\n",line_count,yytext);
				}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 332 "scanner.l"
{printf(" <%s> found\n",yytext);
			//outputfile<<"<DO> ";
			fprintf(tokenout,"<DO> ");
			fprintf(logout,"\nLine no %d: Token <DO> Lexeme %s found\n",line_count,yytext);
			}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 337 "scanner.l"
{printf(" <%s> found\n",yytext);
				//	outputfile<<"<FLOAT> ";
			fprintf(tokenout,"<FLOAT> ");
			fprintf(logout,"\nLine no %d: TOKEN <FLOAT> Lexeme %s found\n",line_count,yytext);
					
					}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 343 "scanner.l"
{printf(" <%s> found\n",yytext);
			SymbolTable sTable(7);
				// outputfile<<"<VOID> ";
			fprintf(tokenout,"<VOID> ");
			fprintf(logout,"\nLine no %d: Token <VOID> Lexeme %s found\n",line_count,yytext);
				}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 349 "scanner.l"
{printf(" <%s> found\n",yytext);
		//outputfile<<"<INT> ";	
			fprintf(tokenout,"<INT>");
			fprintf(logout,"\nLine no %d: TOKEN <INT> Lexeme %s found\n",line_count,yytext);
		
			}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 355 "scanner.l"
{printf(" <%s> found\n",yytext);
			//outputfile<<"<CHAR> ";
			fprintf(tokenout,"<CHAR> ");
			fprintf(logout,"\nLine no %d: TOKEN <CHAR> Lexeme %s found\n",line_count,yytext);
			}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 360 "scanner.l"
{   printf("<%s> found\n",yytext);
			//outputfile<<"<WHILE> ";
			fprintf(tokenout,"<WHILE> ");
			fprintf(logout,"\nLine no %d: TOKEN <WHILE> Lexeme %s found\n",line_count,yytext);
	
		}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 366 "scanner.l"
{

			printf("<%s> found\n",yytext);
			fprintf(tokenout,"<BREAK>");
			fprintf(logout,"\nLine no %d: TOKEN <BREAK> Lexeme %s found\n",line_count,yytext);
	//outputfile<<"<BREAK> ";
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 374 "scanner.l"
{

	printf("<%s> found\n",yytext);
				fprintf(tokenout,"<DOUBLE> ");
			fprintf(logout,"\nLine no %d: TOKEN <DOUBLE> Lexeme %s found\n",line_count,yytext);
	//outputfile<<"<DOUBLE> ";
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 382 "scanner.l"
{

	printf("<%s> found\n",yytext);
	//outputfile<<"<RETURN> ";
				fprintf(tokenout,"<RETURN> ");
			fprintf(logout,"\nLine no %d: Token <RETURN> Lexeme %s found\n",line_count,yytext);
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 389 "scanner.l"
{

	printf("<%s> found\n",yytext);
	//outputfile<<"<CASE> ";
				fprintf(tokenout,"<CASE> ");
			fprintf(logout,"\nLine no %d: TOKEN <CASE> Lexeme %s found\n",line_count,yytext);
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 396 "scanner.l"
{

	printf("<%s> found\n",yytext);
				fprintf(tokenout,"<CONTINUE> ");
			fprintf(logout,"\nLine no %d: Token <CONTINUE> Lexeme %s found\n",line_count,yytext);
	//outputfile<<"<CONTINUE> ";
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 405 "scanner.l"
{printf("TAB <\t> found\n");
			fprintf(tokenout,"<CONST_CHAR, \t> ");
			fprintf(logout,"\nLine no %d: Token <CONST_CHAR> Lexeme \t found\n",line_count);
			//sTable.push("COMMA",yytext);
	//	outputfile<<"<COMMA, "<<yytext;
		}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 411 "scanner.l"
{printf("SPECIALS <%s> found\n",yytext);
			fprintf(tokenout,"<CONST_CHAR, %s> ",yytext);
			fprintf(logout,"\nLine no %d: Token <CONST_CHAR> Lexeme %s found\n",line_count,yytext);
			//sTable.push("COMMA",yytext);
	//	outputfile<<"<COMMA, "<<yytext;
		}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 418 "scanner.l"
{printf(" <%s> found\n",yytext);
			fprintf(tokenout,"<COMMA, %s> ",yytext);
			fprintf(logout,"\nLine no %d: Token <COMMA> Lexeme %s found\n",line_count,yytext);
			//sTable.push("COMMA",yytext);
	//	outputfile<<"<COMMA, "<<yytext;
		}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 424 "scanner.l"
{printf(" <%s> found\n",yytext);
			fprintf(tokenout,"<LTHIRD, %s> ",yytext);
			fprintf(logout,"\nLine no %d: Token <LTHIRD> Lexeme %s found\n",line_count,yytext);
			//sTable.push("LTHIRD",yytext);
	//	outputfile<<"<LTHIRD, "<<yytext;
	}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 430 "scanner.l"
{printf(" <%s> found\n",yytext);
			fprintf(tokenout,"<RTHIRD, %s> ",yytext);
			fprintf(logout,"\nLine no %d: Token <RTHIRD> Lexeme %s found\n",line_count,yytext);	
			//sTable.push("RTHIRD",yytext);	

		//outputfile<<"<RTHIRD, "<<yytext;
	}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 439 "scanner.l"
{printf(" <SEMICOLON, %s> found\n",yytext);
			fprintf(tokenout,"<SEMICOLON, %s> ",yytext);
			fprintf(logout,"\nLine no %d: Token <SEMICOLON> Lexeme %s found\n",line_count,yytext);
			//sTable.push("SEMICOLON",yytext);
		
		//outputfile<<"<SEMICOLON, "<<yytext;
	}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 446 "scanner.l"
{printf(" <%s> found\n",yytext);
			fprintf(tokenout,"<LCURL, %s> ",yytext);
			fprintf(logout,"Line no %d: Token <LCURL> Lexeme %s found\n",line_count,yytext);
		
		//outputfile<<"<LCURL, "<<yytext;
	}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 452 "scanner.l"
{printf(" <%s> found\n",yytext);
			fprintf(tokenout,"<RCURL, %s> ",yytext);
			fprintf(logout,"\nLine no %d: Token <RCURL> Lexeme %s found\n",line_count,yytext);
		
		//outputfile<<"<LCURL, "<<yytext;
	}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 458 "scanner.l"
{printf(" <%s> found\n",yytext);
			fprintf(tokenout,"<LPAREN, %s> ",yytext);
			fprintf(logout,"\nLine no %d: Token <LPAREN> Lexeme %s found\n",line_count,yytext);
		
		//outputfile<<"<LPAREN, "<<yytext;
	}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 464 "scanner.l"
{printf(" <%s> found\n",yytext);
			fprintf(tokenout,"<RPAREN, %s> ",yytext);
			fprintf(logout,"\nLine no %d: Token <RPAREN> Lexeme %s found\n",line_count,yytext);
		//outputfile<<"<RPAREN, "<<yytext;
	}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 469 "scanner.l"
{printf(" <%s> found\n",yytext);
			fprintf(tokenout,"<NOT, %s> ",yytext);
			fprintf(logout,"\nLine no %d: Token <NOT> Lexeme %s found\n",line_count,yytext);
		
		//outputfile<<"<NOT, "<<yytext;
	}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 477 "scanner.l"
{

		printf(" <%s> found\n",yytext);
			fprintf(tokenout,"<LOGICOP, %s> ",yytext);
			fprintf(logout,"\nLine no %d: Token <LOGICOP> Lexeme %s found\n",line_count,yytext);		
		///outputfile<<"<LOGICOP, "<<yytext;
	}
	YY_BREAK
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 488 "scanner.l"
{

					printf("<STRING , %s>\n",yytext);
					string str(yytext);

					char output[str.length()];
					char output2[str.length()];

					strcpy(output,str.c_str());
					char qq;
					
					fprintf(tokenout,"<STRING, ");


					
					for(int i=0;i<strlen(yytext);i++){
						if(output[i]=='\\' && output[i+1]=='t'){
							  output2[i]='\t';
							  qq = '\t';
							  printf("%c",qq);
							  fprintf(tokenout,"%c",qq);
							 
							  i++;
							  continue;

						}
						else if (output[i]=='\\' && output[i+1]=='n') {
							output2[i] = '\n';
							qq = '\n';
							  printf("%c",qq);
							   fprintf(tokenout,"%c",qq);
							i++;
							continue;
						}
						
						else if (output[i]=='\\' && output[i+1]=='b') {
							output2[i]='\b';
							qq = '\b';
							  printf("%c",qq);
							   fprintf(tokenout,"%c",qq);
							i++;
							continue;
						}
						else if(output[i]=='\n'){
							if(output[i-1]=='\\'){
								line_count++;
								
								continue;
							}

							output2[i]='\n';
							qq = '\n';
							  printf("%c",qq);
							   fprintf(tokenout,"%c",qq);
							line_count++;
							
							continue;
						}
						else if(output[i]=='\\'){
							
							

						}
						

						
						else {
							output2[i] = output[i];

							printf("%c",output[i]);
							 fprintf(tokenout,"%c",output[i]);
						}

					}
					cout<<endl;
					
				
				
					
					

				}
	YY_BREAK
case 57:
/* rule 57 can match eol */
YY_RULE_SETUP
#line 570 "scanner.l"
{

								printf("literlas not finished, %s",yytext);
								fprintf(logout,"\nError at line no %d: Unterminated String %s",line_count,yytext);
								line_count+=2;
								error_count++;

								}
	YY_BREAK
case 58:
/* rule 58 can match eol */
YY_RULE_SETUP
#line 578 "scanner.l"
{
			printf("UNFINISHED literlas: %s\n",yytext); 
			fprintf(logout,"\nError at line no %d: Unterminated String %s",line_count,yytext);
			line_count++;
			error_count++;

				}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 587 "scanner.l"
{printf("%s CONST_INT\n",yytext);
			fprintf(tokenout,"<CONST_INT, %s> ",yytext);
			fprintf(logout,"\nLine no %d: Token <INT> Lexeme %s found\n",line_count,yytext);
			}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 592 "scanner.l"
{printf("%s CONST_FLOAT\n",yytext);
			fprintf(tokenout,"<CONST_FLOAT, %s> ",yytext);
			fprintf(logout,"\nLine no %d: Token <CONST_FLOAT> Lexeme %s found\n",line_count,yytext);
			}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 597 "scanner.l"
{printf("ASSIGNOP <%s> found\n",yytext);
			fprintf(tokenout,"<ASSIGNOP, %s> ",yytext);
			fprintf(logout,"\nLine no %d: Token <ASSIGNOP> Lexeme %s found\n",line_count,yytext);
		
		//outputfile<<"<ASSIGNOP, "<<yytext;
	}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 605 "scanner.l"
{printf("IDENTIFIER <%s> found\n",yytext);
			fprintf(tokenout,"<ID, %s> ",yytext);
			fprintf(logout,"\nLine no %d: Token <ID> Lexeme %s found\n",line_count,yytext);
		
		//outputfile<<"<ID, "<<yytext;
	}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 617 "scanner.l"
{printf("<%s, MULOP>\n",yytext);
			fprintf(tokenout,"<MULOP, %s> ",yytext);
			fprintf(logout,"Line no %d: TOKEN <MULOP> Lexeme %s found\n",line_count,yytext);
			}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 621 "scanner.l"
{printf("<%s, ADDOP>\n",yytext);
			fprintf(tokenout,"<ADDOP, %s> ",yytext);
			fprintf(logout,"Line no %d: TOKEN <ADDOP> Lexeme %s found\n",line_count,yytext);
			}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 626 "scanner.l"
{printf("<%s incop>\n",yytext);
			fprintf(tokenout,"<INCOP, %s> ",yytext);
			fprintf(logout,"Line no %d: TOKEN <INCOP> Lexeme %s found\n",line_count,yytext);
			}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 630 "scanner.l"
{printf("%s RELOP\n",yytext);
			fprintf(tokenout,"<RELOP, %s> ",yytext);
			fprintf(logout,"Line no %d: TOKEN <RELOP> Lexeme %s found\n",line_count,yytext);
			}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(END_WITH_SQ):
case YY_STATE_EOF(END_WITH_DQ):
case YY_STATE_EOF(STRING_LIT):
case YY_STATE_EOF(SLINECOMMENT):
case YY_STATE_EOF(MULTILINECOMMENT):
case YY_STATE_EOF(MSCOMMENT):
case YY_STATE_EOF(DUMMY):
#line 637 "scanner.l"
{printf("Total Line Number: %d \n",line_count);
		
		printf("Total errors: %d \n",error_count);
		 fprintf(logout,"\nTotal lines: %d\n",line_count);
		 fprintf(logout,"Total errors: %d",error_count);
		  return 0;
		}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 644 "scanner.l"
{}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 646 "scanner.l"
ECHO;
	YY_BREAK
#line 1796 "scanner.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 275 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 275 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 274);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 646 "scanner.l"



int main(int argc,char *argv[]){

	
	
	if(argc!=2){
		printf("Please provide input file name and try again\n");
		return 0;
	}
	

	FILE *fin=fopen(argv[1],"r");
	if(fin==NULL)
	{
		printf("Cannot open specified file\n");
		return 0;
	}
	
	logout= fopen("log.txt","w");
	tokenout= fopen("token.txt","w");

	yyin= fin;
	yylex();
	fclose(yyin);
	fclose(tokenout);
	fclose(logout);
	return 0;
}


